wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    t:
      1:
      - 5
      2:
      - 5
      4: 3.9.13
      5: 0.10.31
      8:
      - 5
input:
  desc: null
  value: clean_sample.csv:latest
random_seed:
  desc: null
  value: 42
stratify_by:
  desc: null
  value: none
test_size:
  desc: null
  value: 0.2
