wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    t:
      4: 3.9.13
      5: 0.10.31
      8:
      - 5
artifact_description:
  desc: null
  value: Raw file as downloaded
artifact_name:
  desc: null
  value: sample.csv
artifact_type:
  desc: null
  value: raw_data
sample:
  desc: null
  value: sample1.csv
